# Data Bootcamp Midterm Preparation

## Class 1 - September 5th - Introduction: Data + Python = Magic!

### Mathematical Functions and Variable Assignment

In [2]:
x = 5 #Variable Assignment, also note that equals sign does not mean equal
y = 5
dog_1 = 'corgi' #Variables don't need to be single letters, they can be text
x + 5 #Addition
x - 5 #Subtraction
x * 5 #Multiplication
x / 5 #Division
x ** 5 #Exponents
x % 5 #Remainder of division by the latter value
x // 5 #Rounding down greatest integer division
(x**5)*(.4) #Parentheses work mathematically

1250.0

In [4]:
x,y #single cell variable pair printing

(5, 5)

In [5]:
print(x) #print function

5


In [6]:
import sys      # import system module (don't ask)
print('\nWhat version of Python?\n', sys.version, '\n', sep='')
if float(sys.version_info[0]) < 3.0:
    raise Exception('Program halted, old version of Python. \n',
                     'Sorry, you need to install Anaconda again.')
else:
    print('Congratulations, you have Python 3!')


What version of Python?
3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]

Congratulations, you have Python 3!


In [8]:
#x_1=(((b*(-1))+((b**2)-(4*a*c))**(1/2))/(2*a))
#x_2=(((b*(-1))-((b**2)-(4*a*c))**(1/2))/(2*a))
#print(x_1)
#print(x_2)
#Quadratic Formula, just as a bonus

Downloading a Jupyter Notebook from Github

    First go to the notebook github page and then click on Raw.

    Then, press command+s (ctrl+s if you are using windows) to save it as .ipynb.

    Go to location where you saved .ipynb file.

    Open file, you will see the code.

## Class 2 - September 10th - Introduction(TF's Recitation)

There was nothing significantly new on this lecture day, as far as I can recall. Just more on basic functions and variable assignment.

## Class 3 - September 12th - Python Fundamentals 1

Reminder: Cells are not linked in python, so you can reassign variables using the same variable plus some other value. The output value will totally depend on the order that you run the cell.

In [9]:
#Example of the principle

In [10]:
x = 3

In [11]:
x= x+3

In [12]:
x

6

In [13]:
y = x

In [14]:
x = x+3

In [15]:
print(y)
print(x)

6
9


In [16]:
print(x,y,sep='||||') #seperation notation in print function

9||||6


In [21]:
print?
#? provides information about any function or method in python

In [22]:
type('hello') #The type function. Returns back the type of a given object, like lists, strings, tuples, dictionaries, floats, and integers.
#There are more types outside of base python, like series and dataframes in pandas

str

In [23]:
z = 'hello' #variables can be assigned to strings, and can be concatenated

In [24]:
z+z

'hellohello'

In [25]:
z*10

'hellohellohellohellohellohellohellohellohellohello'

In [27]:
z+x #strings cannot be concatenated with numbers

TypeError: must be str, not int

In [28]:
h = '1234' #Numbers can be strings

In [30]:
first = 'Thomas'
last = 'Hurtubise'
full=first+' '+last
print(full)
#full name code

Thomas Hurtubise


In [31]:
#Including apostrophes and quotation marks in strings:
p = "what's up"
q = """ he said "what's up?" """


In [32]:
print(p)
print(q)

what's up
 he said "what's up?" 


In [33]:
#Lists
#Setting up a list
list1=[0,5,6,22]
print(type(list1))
list1

<class 'list'>


[0, 5, 6, 22]

In [34]:
#Lists can have non-numerical inputs
list2 = [75,'porkchops',4.3]

In [35]:
#lists can contain lists
list3 = [list1,list2]
list3

[[0, 5, 6, 22], [75, 'porkchops', 4.3]]

In [36]:
#we can add lists into a single list
list1+list2

[0, 5, 6, 22, 75, 'porkchops', 4.3]

In [37]:
#making a tuple
type((0,4,5))

tuple

In [38]:
#making a dictionary with key:value pairs
bsch = {'nyu':'stern','penn':'wharton','mit':'sloan'}

In [39]:
#calling a value using a dictionary key. Note we cannot call the key with the value.
bsch['mit']

'sloan'

In [41]:
bsch['michigan']='ross'
# how to add to dictionary. Also works with existing keys to reassign the values

In [42]:
bsch['nyu']=['cas','stern'] #Dictionary values can be lists

In [43]:
#type change functions
x = 2000
str(x) #changes x to a string (does not store as x)

'2000'

In [44]:
type(x)

int

In [45]:
type(str(x))

str

In [46]:
int(str(x)) #integer function to change something to an integer

2000

In [47]:
z=str(int(int(x)/y))
z #produces largest whole integer resulting from the division as a string

'333'

In [48]:
z=str(int(x)//y)
z #another way of producing the largest whole integer resulting from the division as a string

'333'

In [49]:
round #the round function can be used to specify exactly how many decimal places we want to include from a function

<function round>

In [50]:
year = '2018'
nextyear = str(int(year)+1) #Year and next year code

In [51]:
#Date and time code
import datetime as dt
print('Welcome to Data Bootcamp!')
print('Today is: ', dt.date.today())

Welcome to Data Bootcamp!
Today is:  2018-10-20


Bold and italics. If we put a word or phrase between double asterisks, it's displayed in bold. Thus **bold** displays as bold. If we use single asterisks, we get italics: *italics* displays as italics.

Bullet lists. If we want a list of items marked by bullets, we start with a blank line and mark each item with an asterisk on a new line:

* something
* something else
Try it and see.

Links. We construct a link with the text in square brackets and the url in parentheses immediately afterwards. Try this one:

[Data Bootcamp course](http://nyu.data-bootcamp.com/)

Just click in to see the actual code

name error: we have used a variable or function that we have not defined so that python doesn't understand.

That's the general structure of functions in Python: a function name (in this case print) followed by inputs ("arguments" or "parameters") in parentheses that are separated by commas. 

In [52]:
message = 'The value of z is '
print(message, z) #using print for readability

The value of z is  333


In [53]:
longstring = """
Four score and seven years ago
Our fathers brought forth. """
print(longstring) #Triple quotes can also define multi-line strings


Four score and seven years ago
Our fathers brought forth. 


Lists are one of the fundamental Python data structures, a term that means a specific organization of data. 

And a list is ordered, meaning that each item has a particular position

Tuples are ordered collections of things in parentheses separated by commas. They're like lists but the syntax is different (parentheses rather than square brackets) and they can't be changed (experts would say they're "immutable"). We won't use them much but you're likely to run across them now and then in others' code.

In dictionaries,  The keys must be unique, but the values need not be.


In [55]:
print(len(12.24))
print(len('12.24')) #The len function tells us the length of an object

TypeError: object of type 'float' has no len()

In [56]:
print(len('12.24')) #The len function tells us the length of an object

5


In [57]:
float(1) #The float function also works to convert types

1.0

In [58]:
st1 = 'abc'
list4 = list(st1)
list4 #The list function

['a', 'b', 'c']

Name Error. It happens when we use something not defined, it could be a variable or a function. 

Type Error. This one happens all the time too. It happens when an inappropriate operation or function is applied to that specific data type. 

Key Error. Python raises a KeyError whenever a dict() object is requested (using the format a = adict[key]) and the key is not in the dictionary.

Invalid Syntax. Syntax errors can be detected before your program begins to run. These types of errors are usually typing mistakes (fat fingers), but might be hard to find out at first



## Class 4 - September 17th - Python Fundamentals 2

In [59]:
#Boolean Logic
5==4 #using == will check the equivalence of both sides, and return a true or false

False

In [60]:
5==(10/2)

True

In [61]:
type(5==4)

bool

In [62]:
(5==5)+3 #Boolean True is equal to 1. Think like binary

4

In [64]:
(5==4)+3 #Boolean False equals 0

3

In [65]:
#Other self-explanatory boolean expressions (they do not have to be in print, that's just to show all results)
print(5<4)
print(5>4)
print(5>=4)
print(5!=4)
print(not(5>4))

False
True
True
True
False


In [66]:
#if elif and else conditional code example
x=6
if x>5:
    print(x,'is greater than 5')
elif x==5:
    print(str(x)+' is equal to 5')
elif x%2==0:
    print('even')
else:
    print(str(x)+' is less than 5')
#Remember, this code will print the first result that is true, so even if multiple conditions work, only one will result

6 is greater than 5


In [67]:
#Slicing
list1 = ['a','b','c','d','e']
list1[2] #This will slice out the third object. Lists are indexed starting with 0

'c'

In [68]:
list1[2:4] #slices a range not inclusive of the final number

['c', 'd']

In [69]:
list1[-1] #slicing starting at the end of the list, there is no negative 0

'e'

In [70]:
list1[1:-1]

['b', 'c', 'd']

In [71]:
list1[:-2] #slices up to the -2 entry

['a', 'b', 'c']

In [72]:
list1[2:] #slices the third entry on

['c', 'd', 'e']

In [73]:
hi = 'hello there'

In [74]:
hi[:5] #slicing also works on strings

'hello'

In [75]:
hi[0:2]+hi[6:8] #we can concatenate slices

'heth'

In [76]:
#some methods

In [77]:
hi.upper() #method making strings all uppercase

'HELLO THERE'

In [78]:
hi.split()[0] #method splitting strings into a list of the words in a string, which one can then slice

'hello'

In [79]:
hi.split()[1]

'there'

In [80]:
hi.find('o') #method returning the first index number for a given character in a string

4

In [81]:
hi.find('z') #this method returns -1 if there is none

-1

In [82]:
hi.find('l')

2

In [83]:
list1.reverse() #method that automatically reverses a list

In [84]:
list1

['e', 'd', 'c', 'b', 'a']

In [85]:
list1.index('e') #method returning the index number for a given item in a list

0

In [86]:
#Character in a string search code
char = 'e'
if hi.find(char)==-1:
    print('not there')
else:
    print(hi.find(char))

1


In [87]:
#Loops
#basic convention for for loops
for i in list1:
    print(i.upper())

E
D
C
B
A


In [88]:
#For loops work on anything that is iterable, including strings
for i in hi:
    print(i.upper())

H
E
L
L
O
 
T
H
E
R
E


In [89]:
char = 'e'
c=0
for i in hi:
    if i==char:
        print(c)
    c += 1
#how to find the index number for all of a given character in a string

1
8
10


In [90]:
c=0
for i in hi:
    print(c)
    c += 1
#for loop producing every index number in the string

0
1
2
3
4
5
6
7
8
9
10


In [91]:
#Shows off the range function, which is common in for loops. Range function also does not include final number
for i in range(2,10):
    if i%2==0:
        print(i, 'is even')
    else:
        print(i, 'is odd')

2 is even
3 is odd
4 is even
5 is odd
6 is even
7 is odd
8 is even
9 is odd


In [92]:
'chase'>'bartleby'

True

In [94]:
'chase'>'spencer' #when comparing strings, the boolean expression compares the first letters to assess their value. S is a later letter, and has a higher value than c, meaning the expression is false 

False

https://en.wikipedia.org/wiki/List_of_Unicode_characters has the full list of values for characters

In [98]:
ord('c') #this function returns the unicode value for the letters and other characters

99

In [99]:
ord('b')

98

In [100]:
ord('s')

115

In [102]:
#General format for conditionals/ if else statements

if:
    print('if branch')             # do if true
else:
    print('else branch')           # do if false

SyntaxError: invalid syntax (<ipython-input-102-54418f1e35f0>, line 3)

In [103]:
string_1 = 'this is a pretty long string that would be hard to index by hand' 

In [106]:
c=0 #For loop that automatically indexes strings, probably also works with lists
for i in string_1:
    print(i,c)
    c+=1

t 0
h 1
i 2
s 3
  4
i 5
s 6
  7
a 8
  9
p 10
r 11
e 12
t 13
t 14
y 15
  16
l 17
o 18
n 19
g 20
  21
s 22
t 23
r 24
i 25
n 26
g 27
  28
t 29
h 30
a 31
t 32
  33
w 34
o 35
u 36
l 37
d 38
  39
b 40
e 41
  42
h 43
a 44
r 45
d 46
  47
t 48
o 49
  50
i 51
n 52
d 53
e 54
x 55
  56
b 57
y 58
  59
h 60
a 61
n 62
d 63


In [107]:
c=0 #For loop that automatically indexes strings, probably also works with lists
for i in list1:
    print(i,c)
    c+=1

e 0
d 1
c 2
b 3
a 4


In [108]:
numlist = [4, -2, 5] #for loop that sums a list of numbers
total = 0
for num in numlist:
    total = total + num
print(total)

7


In [109]:
numlist = [4, -2, 5] #for loop that sums a list of numbers and then creates an average
total = 0
for num in numlist:
    total = total + num
print(total/len(numlist))

2.3333333333333335


In [110]:
vowels = 'aeiouy' #for loop that checks if letters in a string are vowels
word   = 'anything'
for letter in word:
    if letter in vowels:
        print(letter)

a
y
i


In [111]:
vowels = 'aeiouy' #for loop that checks if letters in a string are consonants
word   = 'anything'
for letter in word:
    if letter not in vowels:
        print(letter)

n
t
h
n
g


In [112]:
for number in range(1, 11): #for loop that prints a number and its square. Illustrates the range function in action
    square = number**2
    print('Number and its square:', number, square)

Number and its square: 1 1
Number and its square: 2 4
Number and its square: 3 9
Number and its square: 4 16
Number and its square: 5 25
Number and its square: 6 36
Number and its square: 7 49
Number and its square: 8 64
Number and its square: 9 81
Number and its square: 10 100


In [113]:
total = 0 #for loop making a sum from a range
for num in range(1, 11):
    total = total + num
print(total)

55


In [114]:
#Loops with conditions. The break command can be used to break loops when a condition is met
maxnum = 20             # guess of number above our limit

total = 0
for num in range(maxnum):
    total = total + num
    if total > 100:
        break              # exit loop
print('At num =', num, 'we had total =', total)

At num = 14 we had total = 105


In [115]:
#break is a special command that ends a loop early.

we can create lists (and do related things) using implicit loops that we refer to as list comprehensions. "Implicit loops" essentially means that they are doing the same thing as a loop, but that the syntax is more compact. This shows up a lot in Python code.

In [116]:
#List comprehension examples

In [117]:
namelist = ['Chase', 'Dave', 'Sarah', 'Spencer']
for item in namelist:
    print(item)

Chase
Dave
Sarah
Spencer


In [118]:
[print(item) for item in namelist]

Chase
Dave
Sarah
Spencer


[None, None, None, None]

In [119]:
[item for item in namelist]

['Chase', 'Dave', 'Sarah', 'Spencer']

In [120]:
fruit = ['apple', 'banana', 'clementine']

In [121]:
FRUIT = [item.upper() for item in fruit]

In [122]:
FRUIT

['APPLE', 'BANANA', 'CLEMENTINE']

In [123]:
fruit6 = [item for item in fruit if len(item)<=6]

In [124]:
fruit6

['apple', 'banana']

In [125]:
g = [0.02, 0.07, 0.07]

In [128]:
percent_growth = [round(dec*100,1) for dec in g]

In [129]:
percent_growth

[2.0, 7.0, 7.0]

In [130]:
#defining functions

In [132]:
#def a very simple function that gives no storable output (meaning it needs no return function)
def hello(firstname):               # define the function
    print('Hello,', firstname)
hello('Chase')                      # use the function

Hello, Chase


In [133]:
def squareme(number): #function with a return, used in practice
    """
    Takes numerical input and returns its square
    """
    return number**2        # this is what the function sends back

square = squareme(7)        # assign the "return" to variable on left
print('The square is', square)

The square is 49


In [134]:
def combine(first, last): #functino combining the first and last names
    """
    Takes strings 'first' and 'last' and returns new string 'last, first'
    """
    lastfirst = last + ', ' + first
    return lastfirst                    # this is what the function sends back

both = combine('Chase', 'Coleman')      # assign the "return" to both
print(both) 

Coleman, Chase


This is a key component of python, which is an object oriented programming language. What does that mean? For us this means that every thing is really an object with associated methods and attributes. A method is like a function that already togo with the given object. Methods in python are always completed with () . Attributes are go-to-go attributes about the object that can be accessed easily. What this means is that there are simple built-in ways to get information and perform operations on objects without having to write our on functions. A typical example is the dict() object which has methods to grab its keys and values, etc.

Functions and methods differ primarily in their syntax:

Syntax of a function: function(object)

Syntax of a method: object.method()

Syntax of a attribute: object.attribute

There are methods and attributes that do many, many things. For those not covered in lectures, we can look them up using tab completion or stack overflow

## Class 5 - September 19th - Python Fundamentals 1 Recitation

In [135]:
bicycles = []
#setting an empty list

In [136]:
#We can extract specific values from a list and use them in other functions
bicycles = ['trek','cannondale','redline','specialized']
message = "My first bicycle was a " + bicycles[1] + '.'
print(message)

My first bicycle was a cannondale.


In [137]:
motorcycles = ['honda','yamaha','suzuki']
motorcycles[0] = 'ducati'
print(motorcycles)
#this will replace a specific entry in a list

['ducati', 'yamaha', 'suzuki']


In [138]:
#adding items to the list, always adds to the end of the list
motorcycles.append('honda')
print(motorcycles)

['ducati', 'yamaha', 'suzuki', 'honda']


In [139]:
#Insterting elements at a specific position (will do so before the entry currently in that position)
motorcycles.insert(0, 'yamaha')
print(motorcycles)

['yamaha', 'ducati', 'yamaha', 'suzuki', 'honda']


In [140]:
#removing elements. You can use the remove function (which you must use if all you know is the value), 
# or if you know the position of the item you can use the del function
print(motorcycles)
del motorcycles[0]
print(motorcycles)
motorcycles.remove('ducati')
print(motorcycles)

['yamaha', 'ducati', 'yamaha', 'suzuki', 'honda']
['ducati', 'yamaha', 'suzuki', 'honda']
['yamaha', 'suzuki', 'honda']


In [141]:
#Sorting a list. The .sort function will change the order of the list permanenetly

cars = ['bmw','audi','toyota','subaru']
print(cars)
cars.sort()
print(cars)

['bmw', 'audi', 'toyota', 'subaru']
['audi', 'bmw', 'subaru', 'toyota']


In [143]:
#This will reverse the sort order of the list
cars.sort(reverse=True)
print(cars)

['toyota', 'subaru', 'bmw', 'audi']


In [144]:
#We can use the sorted function to temporarily look at what a sorted function looks like
print(sorted(cars))
print(cars)
#You could save the sorted list to a new variable to maintain the original list and have the sorted list

['audi', 'bmw', 'subaru', 'toyota']
['toyota', 'subaru', 'bmw', 'audi']


In [145]:
#we can also use the pop function to remove things from the list
cars.pop(3)
print(cars)

['toyota', 'subaru', 'bmw']


In [146]:
#creating dictionaries and adding items

superheroes = {} #making a blank dictionary

#adding (key,value) pairs to a dictionary
superheroes['batman'] = 'bruce wayne'
superheroes['superman'] = 'clark gable'

In [147]:
#we can update a value by simply reassigning it using the same formula as above
superheroes['superman'] = 'clark kent'
print(superheroes)
#counting the number of keys
len(superheroes)

{'batman': 'bruce wayne', 'superman': 'clark kent'}


2

In [148]:
#removing key,value pairs from a dictionary
del superheroes['superman']
print(superheroes)

{'batman': 'bruce wayne'}


In [150]:
superheroes['superman'] = 'clark kent'
#modifying keys
superheroes['supermain']= superheroes['superman'] #write out the new key first, then followed by the one you are replacing
del superheroes['superman'] #we must delete the previous key as well, otherwise it will show up
print(superheroes)

{'batman': 'bruce wayne', 'supermain': 'clark kent'}


In [151]:
#Get a list containing all paris in the dictionary
#Reminder: Dictionaries are not ordered

superheroes.items() #shows the items in the dictionary as a list

dict_items([('batman', 'bruce wayne'), ('supermain', 'clark kent')])

In [152]:
# check if a key is in the dictionary

'james bond'in superheroes #gives a true or fales depending on if the prompt is a key in that dictionary

False

In [154]:
#listing all the keys or values in a dictionary

print(superheroes.keys())
print(superheroes.values())

dict_keys(['batman', 'supermain'])
dict_values(['bruce wayne', 'clark kent'])


In [155]:
#Nested Dictionaries
student = {}
student['alice'] = {'Age':'21','Semester':'Fall 2018','Gender':'F'}
print(student)

{'alice': {'Age': '21', 'Semester': 'Fall 2018', 'Gender': 'F'}}


In [157]:
student['alice']['Age'] #using keys in the nested dictionaries to narrow the search. Also works for slicing indexes of nested lists 
#If one of the elements is a list we can also narrow by list item like student['alice']['subject'][0]

'21'

### the tuple:
- tuple is similar to list
- However, tuple is a sequence immutable objects, that we cannot modify the value once it has been created

In [158]:
# using parenthesis to build up a empty tuple
tuple_empty = ()
type(tuple_empty)

tuple

In [159]:
# created empty tuple, just like list and dictionary but with parentheses
tuple_ex = ('one','two','three','four')
print(tuple_ex)

('one', 'two', 'three', 'four')


In [160]:
# check the lenght of tuple
len(tuple_ex)

4

In [161]:
# immutability of tuples
tuple_ex[0] = '1'

TypeError: 'tuple' object does not support item assignment

In [162]:
# can we append value to tuple, just like list? Yes.
# we don't modify the value
tuple_ex2=('1','2','3','4')
tuple_append = tuple_ex + tuple_ex2
print(tuple_append)

('one', 'two', 'three', 'four', '1', '2', '3', '4')


In [163]:
# use slice to inverse the tuple
tuple_ex2_reverse = tuple_ex2[::-1] 
print(tuple_ex2_reverse)
# does the order matter? Yes
print(tuple_ex2_reverse == tuple_ex2)

('4', '3', '2', '1')
False


In [165]:
# since list and tuple all are seqence of value, can we convert them to each other?
# can we convert list to tuple? Yes
print(tuple(['one', 'two', 'three', 'four', '1', '2', '3', '4']))
# can we convert tuple to list? Yes
list(tuple_append)

('one', 'two', 'three', 'four', '1', '2', '3', '4')


['one', 'two', 'three', 'four', '1', '2', '3', '4']

In [166]:
# tuple unpack, 4 elements
first, second, third, fourth = tuple_ex
print(first)
print(second)
print(third)
print(fourth)

one
two
three
four


In [167]:
# tuple unpack, 4 elements, use * Asterisk
first, second,  *rest= tuple_ex

In [168]:
print(first)
print(second)
print(rest)

one
two
['three', 'four']


slice syntax with brackets and colon: [start : end(not inclueded) : increment]

In [169]:
# slice the tuple to get the value, just like the list
print(tuple_ex[-1])
print(tuple_ex[0:3])
print(tuple_ex[0:3:2])
# the last comma is optional
print(tuple_ex[:])
print(tuple_ex[::])

four
('one', 'two', 'three')
('one', 'three')
('one', 'two', 'three', 'four')
('one', 'two', 'three', 'four')


In [170]:
#sets are dictionaries with only keys
set_example = {'one', 'two', 'three', 'four'}
set_example.add('five')
set_example

{'five', 'four', 'one', 'three', 'two'}

In [ ]:
%%timeit #complicated for loop
e = []
for i in range(10**4) :

    for j in range(i,10**4):

            if i==j:
                e.append(i+j)
            else:
                e.append((i,j))

In [ ]:
%%timeit #complicated list comprehension doing the same thing
d = [(i+j) if i==j else (i,j) for i in range(10**4) for j in range(i,10**4)]

## Class 6 - September 24th - Python Fundamentals 2 Recitation

In [175]:
#Ignoring Case When Checking for Equality
#case sensitive by default
##Testing for equality is case sensitive in Python


car = 'Audi'

car == 'audi'

False

In [176]:
##lower fucntion to convert the variables values to lower case for comparison

car.lower() == 'audi'

True

In [177]:
##use the != sign to check for inequality
pizza_topping  = 'mushrooms'
pizza_topping!= 'cheese'

True

In [181]:
##using 'and' to check multiple conditions
age_1  = 21
passport_1 = 'Yes'


age_2 = 25
passport_2 = 'No'

In [182]:
age_1 >= 21 and passport_1  == 'Yes'

True

In [183]:
##even if one of the check fails , entire check fails  --- > this is the importance of the and keyword.

age_2 >= 21 and passport_2 == 'Yes'

False

In [184]:
##using or to check multiple conditions
gre_score_1 = 320

gpa_1 = 3.2

gre_score_2 = 304

gpa_2 = 3.7

gre_score_1 >= 315 or gpa_1 > 3.5

True

In [185]:
gre_score_2 >= 315 or gpa_2 > 3.5

True

In [186]:
## in keyword checks if a value is there in a list or not
pizza_top = ['cheese', 'mushrooms', 'chicken']
'cheese' in pizza_top

True

In [187]:
##However, sometimes it’s important to check all of the conditions of interest. 
##In this case, you should use a series of simple if statements with no elif or else blocks.
requested_toppings = ['mushrooms', 'extra cheese']


if 'mushrooms' in requested_toppings: 
    print("Adding mushrooms.")
    
if 'pepperoni' in requested_toppings: 
    print("Adding pepperoni.")
    
if 'extra cheese' in requested_toppings: 
    print("Adding extra cheese.")
    
    
print("\nFinished making your pizza!")

Adding mushrooms.
Adding extra cheese.

Finished making your pizza!


In [189]:
# to create a modified list in a for loop, you create a new empty list and add the modified values to it:
oscar_movies = ['get out', 'dunkirk', 'ladybird', 'darkest hour', 'call me by your name', 'the shape of water']
modified_oscar_movies = [] # create new empty list where we will store the modified values

for movie in oscar_movies: # we iterate over the original list
    modified_movie = 'Oscar-nominee %s' % movie #using %s to call a string
    modified_oscar_movies.append(modified_movie) # .append() the modified values to the new list we just created 
    
# finally, remember to replace the original list with the newly created one
oscar_movies = modified_oscar_movies

print(oscar_movies)

['Oscar-nominee get out', 'Oscar-nominee dunkirk', 'Oscar-nominee ladybird', 'Oscar-nominee darkest hour', 'Oscar-nominee call me by your name', 'Oscar-nominee the shape of water']


In [192]:
# using a for loop with a dictionary:


# key is the state, value is the city
state_capitals = {'Washington': 'Olympia', 'California': 'Sacramento', 'New York': 'Albany', 'Florida': 'Tallahassee'}

# print a sentence using each of the (key, value) pairs in our dictionary
#%s with dictionary
for state in state_capitals.keys():
    print("%s is the capital of %s!" % (state_capitals[state], state))  

Olympia is the capital of Washington!
Sacramento is the capital of California!
Albany is the capital of New York!
Tallahassee is the capital of Florida!


In [193]:
#There are other items from this recitation like deep copying that we never covered in any other space. 
#Know that it is there just in case

## Class 7 - September 26th - Python Fundamentals 3

In [194]:
#Clock function
def clock(h,m):
    h_angle = (h*30) + (m*.5)
    m_angle = (m*6)
    if abs(h_angle - m_angle) <= 180:
        angle = abs(h_angle - m_angle)
    else:
        angle = 360 - abs(h_angle - m_angle)
    
    return(angle)

In [195]:
#packages - numpy
import numpy as np

In [196]:
#some basic numpy methods, square root and log
np.sqrt(10)
np.log(10)

2.302585092994046

In [197]:
#numpy arrays
ar = np.array([3,4,5,6]) #making an array using the array method

In [198]:
ar

array([3, 4, 5, 6])

In [199]:
#actions on arrays

In [200]:
ar.max()

6

In [201]:
np.sqrt(ar)

array([1.73205081, 2.        , 2.23606798, 2.44948974])

In [204]:
ar.shape #shape attribute shows dimensions. In this case its a 1x4 but because we did not define it as a matrix, it reads as 4

(4,)

In [205]:
ar2 = np.array([[2,3,4],[11,5,6]]) #The extra set of brackets is how you define it as a matrix in numpy. 
#We can even do this for one row of data

In [206]:
ar2

array([[ 2,  3,  4],
       [11,  5,  6]])

In [207]:
ar2.shape

(2, 3)

In [208]:
ar2.T #transpose numpy array

array([[ 2, 11],
       [ 3,  5],
       [ 4,  6]])

In [209]:
ar2*3 #broadcasting, multiplies everything in an array by a value in numpy

array([[ 6,  9, 12],
       [33, 15, 18]])

In [210]:
ar2.T.shape #we can layer the methods and attributes

(3, 2)

In [212]:
%%time 
#tells one how long it takes to run a function
ar2*3

Wall time: 0 ns


array([[ 6,  9, 12],
       [33, 15, 18]])

In [213]:
#Importing pandas
import pandas as pd

The word package here refers to plug-ins or extensions that expand Python's capabilities. Terminology varies. What we call a package others sometimes call a "library." The term "module" typically refers to a subset of core Python or one of its packages. You won't go far wrong to use the terms interchangeably.

Some of the leading packages for numerical ("scientific") computation are

​Pandas. The leading package for managing data

​Matplotlib. The leading graphics package. We'll use it extensively.

​NumPy. Tools for numerical computing. In Excel the basic unit is a cell, a single number. In NumPy the basic unit is a vector (a column) or matrix (a table or worksheet), which allows us to do things with an entire column or table in one line. This facility carries over to Pandas.

from xyz import foo

This imports the foo function directly so it can be called with foo()

from xyz import *. This imports all the functions and methods from the package xyz, but here the function foo is executed simply by typing foo. We don't usually do this, because it opens up the possibility that the same function exists in more than one package, which is virtually guaranteed to create confusion.

In [214]:
#Always do this importation
import pandas as pd                  # data package
import matplotlib.pyplot as plt      # graphics package

In [215]:
#checking pandas version number to assess errors
import pandas as pd
print('Pandas version ', pd.__version__)       # these are double underscores

Pandas version  0.23.0


In [216]:
#There is a section in the book on conda and pip which we did not cover in class, just know they are there in the packages chapter

In [217]:
data1 = [3.4,2,7,1,5]
arr1 = np.array(data1)
data2 = [5,2,1,3,4]
arr2 = np.array(data2)

In [219]:
arr1 + arr2 #We can add arrays

array([8.4, 4. , 8. , 4. , 9. ])

In [220]:
arr1*arr2 #We can multiply the terms in two arrays by respective terms in the other array

array([17.,  4.,  7.,  3., 20.])

In [221]:
arrZeros = np.zeros((2,3)) #method to create a 2x3 array with zeroes
arrZeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [222]:
arrOnes = np.ones((2,2)) #method to create a 2x2 array with ones
arrOnes

array([[1., 1.],
       [1., 1.]])

In [223]:
arrEyes = np.eye(3) #method to create a 3x3 identity matrix
arrEyes

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [227]:
np.arange(0,10,2) #creates an array over a range (start,stop,increment)

array([0, 2, 4, 6, 8])

In [229]:
arr3 = arr1+2 #broadcasting works with addition as well
arr3

array([5.4, 4. , 9. , 3. , 7. ])

In [230]:
np.eye?

In [231]:
(arrEyes+2)-arrEyes*3

array([[0., 2., 2.],
       [2., 0., 2.],
       [2., 2., 0.]])

In [232]:
#Slicing arrays
arr4=np.array([[2,3,4],[8,5,7]])
arr4

array([[2, 3, 4],
       [8, 5, 7]])

In [233]:
arr4[0,1] #slicing by row then column

3

In [238]:
arr4[0][1] #slicing a row then a column

numpy.int32

In [240]:
arr4[0,1:2] #ranges still work when slicing arrays, interestingly this way will maintain the array typing

array([3])

In [241]:
#methods on arrays or arraywise operations
np.sum(arr4) #sums all entries in an array 


29

In [242]:
np.sum(arr4,axis=0) # Column Sum for arrays

array([10,  8, 11])

In [243]:
np.sum(arr4,axis=1) # Row Sum for arrays

array([ 9, 20])

In [244]:
np.random.randn(2,4) #random number generation over a normal distribution for an array of a given shape, in this case 2x4

array([[ 0.53702806, -0.68846137, -0.953181  ,  1.38573204],
       [ 0.67044901, -1.91569487, -0.24557095,  1.50351237]])

## Class 8 - October 1 - Python Fundamentals 3 Recitation

In [245]:
#for loop with if statement and boolean to assess the best asset from a list of lists
portfolio = [['IBM',0.0005],['S&P 500',0.001],['Citi',-0.015],['Facebook',-0.04],['Apple',0.0035]]

best_asset = ''
best_return = -100  # the worst return
for equity in portfolio:
    equity_name = equity[0]  # take out the name
    equity_return = equity[1]   # take out the return
    
    if equity_return>best_return:  # if return is better, we update the name
        best_asset = equity_name
        best_return = equity_return

In [246]:
print(best_asset)
print(best_return)

Apple
0.0035


In [247]:
#Using list comprehensions to do the same thing
list_name = [equity[0] for equity in portfolio]
list_return = [equity[1] for equity in portfolio]

In [248]:
best_return = max(list_return)
best_asset_pos = list_return.index(best_return)

In [249]:
#List comprehension for nested for loop
[(i, j) for i in range(4) for j in range(i)]

[(1, 0), (2, 0), (2, 1), (3, 0), (3, 1), (3, 2)]

In [250]:
#list comprehension with filtering
[(i, j) for i in range(4) for j in range(i) if i%2==0]

[(2, 0), (2, 1)]

In [251]:
#List comprehension with if else conditional statements
[(i, j) if i-j>1 else 'Too small' for i in range(4) for j in range(i)]

['Too small', (2, 0), 'Too small', (3, 0), (3, 1), 'Too small']

In [252]:
#more numpy methods

In [254]:
# Create a 3x3 array of random integers in the interval [0, 10)
rando = np.random.randint(0, 10, (3, 3))
rando

array([[7, 6, 3],
       [8, 5, 0],
       [8, 5, 0]])

In [255]:
#says the dimension of the array. Note, do not confuse with the matrix size.
rando.ndim

2

In [256]:
#Values can also be modified using index notation

rando[0,0] = 9
rando

array([[9, 6, 3],
       [8, 5, 0],
       [8, 5, 0]])

In [258]:
#general slicing syntax for arrays
#array[start:stop:step]
##Multi-dimensional slices work in the same way, with multiple slices separated by commas
rando[0:2,2:]

array([[3],
       [0]])

In [259]:
#selecting all rows in reverse in an array

rando[::-1,]

array([[8, 5, 0],
       [8, 5, 0],
       [9, 6, 3]])

In [260]:
#selecting all the columns in reverse in an array
rando[::,::-1]

array([[3, 6, 9],
       [0, 5, 8],
       [0, 5, 8]])

In [261]:
## reshaping arrays

##use reshape method

##the size of the initial array must match the size of the reshaped array
rando.reshape(9,1)  

array([[9],
       [6],
       [3],
       [8],
       [5],
       [0],
       [8],
       [5],
       [0]])

In [262]:
##Array Concatenation for 1 dimensional arrays
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [263]:
#Array concatenation for 2 dimensional arrays
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
# concatenate along axis 0 i.e row
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [264]:
### concatenate along the axis 1, i.e column

np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [265]:
np.max(x)

3

In [266]:
np.min(x)

1

In [267]:
##Multi dimensional aggregates

##One common type of aggregation operation is an aggregate along a row or column.

p = np.random.randint(1, 15, (3,4))

In [268]:
p

array([[ 1,  4, 14,  1],
       [ 6, 12,  9, 11],
       [ 8, 12, 10,  2]])

In [269]:
#max from each column

np.max(p, axis= 0)

array([ 8, 12, 14, 11])

In [270]:
#max from each row

np.max(p, axis=1)

array([14, 12, 12])

In [271]:
np.prod(p[:1]) #product of a row

56

In [272]:
np.prod(p, axis = 1) #product of all rows

array([  56, 7128, 1920])

In [273]:
#The recitation notes have an interesting section on boolean with arrays that we did not cover at any other point
#I am not including it here.

## Homework 1

In [276]:
x = "luke, i am your father"
x.title() #string method that capitalizes each word

'Luke, I Am Your Father'

In [277]:
# This code converts x into a list of the words in the original string, accomplishing part c
x = x.split(sep=None)
print(x)

['luke,', 'i', 'am', 'your', 'father']


In [278]:
#The rest of the assignment was largely derivative of things we already covered